---
os_configuration:
  # Enabling strict policy will lead to denied access over SSH for not allowed hosts.
  strict_ssh_policy: no
  sshd:
    UsePAM: "yes"
    PermitRootLogin: "prohibit-password"
    AuthorizedKeysFile: "%h/.ssh/authorized_keys"
    PubkeyAuthentication: "yes"
    PasswordAuthentication: "no"
    ChallengeResponseAuthentication: "no"
  # IP addresses uses for whitelisting by NGINX and SSHD. All others will be restricted.
  allowed_hosts:
    - 195.182.195.117
    - 159.224.193.142
