# The "{{ item }}" here must look like:
# item:
#   /etc/environment:
#     VARIABLE1: value1
#     VARIABLE2: value2
---
- name: "Adding variable to the '{{ item.key }}'{{ target | default('') }}"
  lineinfile:
    path: "{{ item.key }}"
    # The "/etc/environment" is a non-regular Shell executable. We
    # must avoid using "export" in there.
    line: '{{ "" if item.key == "/etc/environment" else "export " }}{{ variable.key }}="{{ variable.value }}"'
    regexp: "{{ variable.value | regex_escape }}"
    insertbefore: BOF
  with_dict: "{{ item.value }}"
  loop_control:
    loop_var: variable
