---
- name: Create service
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ item.service.service }}.service"
    mode: 0750

- name: Reload Systemd daemon
  systemd:
    name: "{{ item.service.service }}"
    state: stopped
    daemon_reload: yes
