---
- name: Get the name of original VM
  include: ../vboxmanage.yml
  args:
    command: "list vms | awk '/{{ application }}/ {print $1}'"

- name: Determine a number of a new VM
  set_fact:
    vm_num: "{{ '%02d' | format(vboxmanage_result.stdout_lines | count | int + 1) }}"

- name: Set name for a new VM
  set_fact:
    vm_name: "{{ application }}{{ vm_num }}"

- include: clone.yml
  args:
    name: "{{ vm_path | basename | splitext | first }}"
    new: "{{ vm_name }}"

- name: Get list of all forwarding ports
  include: ../vboxmanage.yml
  args:
    # Example:
    # Forwarding(5)="jenkins,tcp,127.0.0.1,8199,,443"
    command: "showvminfo {{ vm_name }} --machinereadable | awk -F '[\",]' '/^Forwarding/ {print $2}'"

- name: Remove forwarding port
  include: ../vboxmanage.yml
  args:
    command: "modifyvm {{ vm_name }} --natpf1 delete {{ item }}"
  with_items: "{{ vboxmanage_result.stdout_lines }}"

- name: Configure port forwarding for a new VM
  include: ../vboxmanage.yml
  args:
    # Scheme: [<name>],tcp|udp,[<hostip>],<hostport>,[<guestip>],<guestport>
    command: "modifyvm {{ vm_name }} --natpf1 '{{ item.key }},tcp,{{ '127.0.0.1' if item.value.vhost else '' }},{{ item.key }}{{ vm_num }},,{{ item.key }}'"
  with_dict: "{{ virtualmachine.port_forwarding }}"

- include: startvm.yml
  args:
    droplet_name: "{{ vm_name }}"

- name: Print name of newly created droplet
  debug:
    msg: "Droplet '{{ vm_name }}' has been created."
