---
- name: Check whether MySQL is already installed
  stat:
    path: "{{ cikit_mysql.daemon }}"
  register: cikit_mysql_installed

- include: setup.yml
  when: not cikit_mysql_installed.stat.exists

- name: Stop MySQL service
  service:
    name: mysql
    state: stopped

# Temporary directory is configured to be in shared memory (RAM).
- include: shm-tempdir.yml
  when: "'shm' in cikit_mysql.dirs.tmp"

- name: Disable AppArmor
  shell: |-
    update-rc.d -f apparmor remove
    /etc/init.d/apparmor teardown
    /etc/init.d/apparmor stop
  ignore_errors: yes

- name: Setting mysqld to complain mode
  shell: aa-complain /usr/sbin/mysqld
  ignore_errors: yes
  # AppArmor just not working properly inside of Docker containers.
  when: not docker

- name: Compute memory for InnoDB buffers
  shell: "cat /proc/meminfo | awk '/MemTotal/ {print $2/1024*{{ cikit_mysqld_configuration.innodb_buffer_pool_size }}/100}'"
  register: cikit_mysql_innodb_buffer_pool_size

- name: Create MySQL configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - src: mysqld.cnf.j2
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      # 644
      mode: go-r,u-w

    - src: python-my.cnf.j2
      dest: /root/.my.cnf
      # 600
      mode: u-w

- name: Ensure MySQL service is enabled on boot
  service:
    name: mysql
    state: started
    enabled: yes

- name: Remove anonymous MySQL user
  mysql_user:
    name: ""
    state: absent

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
