---
- name: Create Jenkins CLI destination directory
  file:
    path: "{{ jenkins_dest }}"
    state: directory

- name: Get Jenkins CLI
  get_url:
    url: "{{ jenkins_host }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins.cli }}"
    mode: 0440
  until: cli_downloaded is success
  register: cli_downloaded
  retries: 5
  delay: 10

- name: Get updates
  get_url:
    url: "{{ jenkins.updates.url }}/update-center.json"
    dest: "{{ jenkins.updates.file }}"
    mode: 0440
    thirsty: yes
  register: jenkins_updates

- name: Update-center
  shell: |-
    cat '{{ jenkins.updates.file }}' | sed '1d;$d' | curl {{ jenkins_host }}/updateCenter/byId/default/postBack \
      -X POST \
      -H "Accept: application/json" \
      -d @-
  when: jenkins_updates.changed
