---
- name: Wait for Jenkins service
  wait_for:
    port: "{{ jenkins_port }}"
    delay: 10

- name: Create Jenkins CLI destination directory
  file:
    path: "{{ jenkins_dest }}"
    state: directory

- name: Get Jenkins CLI
  get_url:
    url: "{{ jenkins_host }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins.cli }}"
    mode: 0440
  delay: 20
  retries: 5
  register: cli_downloaded
  until: not "failed" in cli_downloaded

- name: Get updates
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins.updates }}"
    mode: 0440
    thirsty: yes
  register: jenkins_updates

- name: Update-center
  shell: "cat {{ jenkins.updates }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- {{ jenkins_host }}/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify: Restart Jenkins
