---
- name: Create view configuration from template
  template:
    src: list-view.xml.j2
    dest: "{{ jenkins_lib }}/list-view.xml"

# See https://issues.jenkins-ci.org/browse/JENKINS-8927#comment-194588
# See https://wiki.jenkins.io/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection
- name: Create list view
  shell: |-
    curl {{ jenkins_host }}/createView?name={{ jenkins_job }} \
      -X POST \
      -H "Content-Type: text/xml" \
      -H "$({{ jenkins_csrf_command }})" \
      -d @{{ jenkins_lib }}/list-view.xml
  args:
    warn: no

- name: Create folders for jobs
  file:
    path: "{{ jenkins_lib }}/jobs/{{ item.name }}"
    owner: "{{ jenkins_data.user }}"
    group: "{{ jenkins_data.group }}"
    state: directory
  with_items: "{{ jenkins_data.jobs }}"

- name: Copy jobs
  template:
    src: "jobs/{{ item.template }}"
    dest: "{{ jenkins_lib }}/jobs/{{ item.name }}/config.xml"
    owner: "{{ jenkins_data.user }}"
    group: "{{ jenkins_data.group }}"
  with_items: "{{ jenkins_data.jobs }}"
