---
- name: Restart service
  service:
    name: jenkins
    state: restarted

- name: Wait until Jenkins start accepting connections
  uri:
    url: "{{ jenkins_host }}/api/json"
    return_content: yes
  register: jenkins_response
  retries: 5
  delay: 2
  until: "'json' in jenkins_response"
