---
commands:
  bash: []
  wp-cli:
    - name: "Checking theme status"
      theme: ["status"]
    - name: "Installing environment-specific plugins"
      plugin: ["install", "plugin-name"]
    - plugin: ["uninstall", "plugin-name1", "plugin-name2"]

wordpress:
  user:
    name: admin
    pass: propeople
