---
- name: Install dependencies
  apt:
    name: "openjdk-{{ jetty_java_version }}-jdk"
    state: installed

- name: Prepare Java folder
  file:
    path: /usr/java
    state: directory

- name: Prepare Java binaries for amd64
  file:
    src: "/usr/lib/jvm/java-{{ jetty_java_version }}-openjdk-amd64"
    dest: /usr/java/default
    state: link
  when: ansible_machine in ["amd64", "x86_64"]

- name: Prepare Java binaries for i686
  file:
    src: "/usr/lib/jvm/java-1.{{ jetty_java_version }}.0-openjdk-i386"
    dest: /usr/java/default
    state: link
  when: ansible_machine == "i686"

- name: Download Solr
  unarchive:
    src: "http://archive.apache.org/dist/lucene/solr/{{ jetty_solr_version }}/solr-{{ jetty_solr_version }}.tgz"
    dest: /opt
    creates: "/opt/solr-{{ jetty_solr_version }}"
    remote_src: yes

- name: Copy actual Solr sources
  shell: rsync -ra /opt/solr-{{ jetty_solr_version }}/example/ /opt/solr/

- name: Copy Jetty settings
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - src: jetty.j2
      dest: /etc/default/jetty

    - src: jetty-logging.xml.j2
      dest: /opt/solr/etc/jetty-logging.xml

- name: Create user
  user:
    name: solr
    comment: "Solr user"
    shell: /sbin/false
    home: /opt/solr

- name: Grant permission to Solr user in his directory
  file:
    path: /opt/solr
    group: solr
    owner: solr
    recurse: yes

- name: Get init.d script for Jetty
  get_url:
    url: https://gist.githubusercontent.com/peterc/404672/raw/77591f254b055a0fc6165df808ded10e1bb02565/jetty
    dest: /etc/init.d/jetty
    mode: 0755

- name: Update services list
  shell: update-rc.d jetty defaults

- include: cores.yml

- name: Ensure jetty is running.
  service:
    name: jetty
    state: started
    enabled: yes
