---
#- include_tasks: "{{ __selfdir__ }}/scripts/tasks/cikit-install.yml"
#
#- include_tasks: "{{ __selfdir__ }}/scripts/tasks/pip-install.yml"
#  args:
#    pip_packages: "{{ api.pip }}"
#
#- include_role:
#    name: "{{ __selfdir__ }}/scripts/roles/cikit-nodejs"
#  vars:
#    nodejs_version: "{{ api.nodejs_version }}"
#
#- include_role:
#    name: "{{ __selfdir__ }}/scripts/roles/ansible-role-mongodb"
#  vars:
#    mongodb_version: "{{ api.mongodb_version }}"

- name: Upload the implementation of the REST server
  synchronize:
    src: files/cikit-rest-api/
    dest: /var/www/cikit-rest-api/

- name: Install Node modules
  shell: npm install
  args:
    chdir: /var/www/cikit-rest-api/
