image: Visual Studio 2017
build: off
version: '{build}'
platform: x64

skip_commits:
  files:
    - README.md
#  message: /\[skip ci\]/

# There's no need to alter the build number for a Pull Request (PR)
# since they don't modify anything.
pull_requests:
  do_not_increment_build_number: true

install:
  - ps: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
  - ps: Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1604 -OutFile ~/Ubuntu1604.zip -UseBasicParsing
  - ps: Expand-Archive ~/Ubuntu1604.zip ~/Ubuntu

#test_script:

notifications:
  - provider: Slack
    auth_token:
      secure: 2CRn8pK+wW0y2WfQFQU6dINb4IRbiJdUQhHwlV4oTjChqfhWifADCsy5Ne92vt1I
    channel: notifications
