# NOTES:
# - Add "[skip DIR]" to commit message and tests from "./tests/travis/DIR" won't be executed.
# - Use "[skip DIR/FILE]" to skip a particular test from "./tests/travis/DIR/FILE".
# - The "[skip ci]" handled by Travis personally so the build even won't be created.
# Examples:
# - git commit -m '#200: [skip bash] Add Python stuff'
# - git commit -m '#201: [skip bash/init][bash/provision] Improve inventory handling'
# - git commit -m '#202: [skip python][bash/provision] Add new CMF'
# IMPORTANT:
# - When skipping a test the extension of a file MUST NOT be specified. If file
#   is "bash/init.sh" then you just use "[skip bash/init]". For "python/test.py"
#   it'll be "[skip python/test]" and so on.
sudo: required
dist: trusty

services:
  - docker

python:
  - "2.7"

env:
  VAGRANT_VERSION: 2.0.2
  ANSIBLE_VERBOSITY: 1

install:
  - sudo pip install ansible
  - sudo bash ./install.sh --no-requirements-check "${TRAVIS_BRANCH}"
  - sudo wget -nv "https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb"
  - sudo dpkg -i "vagrant_${VAGRANT_VERSION}_x86_64.deb"
  - cd /usr/local/share/cikit
  - sudo git fetch origin "${TRAVIS_BRANCH}"
  - sudo git checkout "${TRAVIS_BRANCH}"

script:
  - sudo ./tests/travis/tests-runner/runner.sh ./tests/travis
  - env

notifications:
  slack: cikit:aT0Y9ZQggfbkLoxONJ7Hg1OO
