sudo: required
dist: trusty

services:
  - docker

python:
  - "2.7"

env:
  VAGRANT_VERSION: 2.0.2
  ANSIBLE_VERBOSITY: 2

install:
  - sudo pip install ansible
  - sudo bash ./install.sh --no-requirements-check
  - sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
  - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
  - cd /usr/local/share/cikit
  - sudo git fetch origin ${TRAVIS_BRANCH}
  - sudo git checkout ${TRAVIS_BRANCH}

script:
  - readarray -t ACTIONS < <(awk -vRS="]" -vFS="[" '{print $2}' <<< "$TRAVIS_COMMIT_MESSAGE")
  - find ./tests/travis -type f -name '*.sh' -exec sudo bash {} \;
  - env
