sudo: required
dist: trusty

services:
  - docker

python:
  - "2.7"

env:
  VAGRANT_VERSION: 2.0.2
  ANSIBLE_VERBOSITY: 2

install:
  # @todo See lib/variables.py
  - sudo pip install ansible==2.5.0
  - sudo bash ./install.sh --no-requirements-check
  - sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
  - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
  - cd /usr/local/share/cikit
  - sudo git fetch origin ${TRAVIS_BRANCH}
  - sudo git checkout ${TRAVIS_BRANCH}

script:
  - cd ./tests/travis
  - |
    declare -A TESTS=([bash]=sh [python]=py)

    # Parse the commit message that looks like "#120: [skip bash/init.sh][ skip  python] Commit name".
    # The resulting string will be: "|skipbash/init.sh|skippython|"
    PARAMS="|$(awk -vRS="]" -vFS="[" '{print $2}' <<< "$TRAVIS_COMMIT_MESSAGE" | head -n -1 | tr '\n' '|' | tr -d [[:space:]])"

    for INTERPRETER in "${!TESTS[@]}"; do
      if [[ ! "$PARAMS" =~ \|skip$INTERPRETER\| ]]; then
        find "$INTERPRETER" -name "[a-z]*.${TESTS[$INTERPRETER]}" -type f | while read -r TEST; do
          if [[ ! "$PARAMS" =~ \|skip$TEST\| ]]; then
            echo "-- Running $TEST..."
            sudo ${INTERPRETER} "$TEST"
          fi
        done
      fi
    done
  - env
