sudo: required
dist: trusty

python:
  - "2.7"

install:
  - bash ./tests/ansible.sh
  - bash ./tests/virtualbox.sh ubuntu 64 /usr/local/share/vb
  - bash ./tests/vagrant.sh ubuntu 64 /usr/local/share/vg
  - bash ./install.sh

script:
  - cikit init --project=test_project
