sudo: required
dist: trusty

python:
  - "2.7"

addons:
  apt:
    packages:
      - build-essential
      - libffi-dev
      - libssl-dev

install:
  - sudo bash ./tests/ansible.sh
  - sudo bash ./tests/virtualbox.sh ubuntu 64 /usr/local/share/vb
  - sudo bash ./tests/vagrant.sh ubuntu 64 /usr/local/share/vg
  - sudo bash ./install.sh

script:
  - cikit init --project=test_project
