sudo: required
dist: trusty

python:
  - "2.7"

addons:
  apt:
    packages:
      - vagrant

install:
  - sudo bash ./tests/ansible.sh
  - sudo bash ./install.sh --no-requirements-check

script:
  - cikit init --project=test_project
