sudo: required
dist: trusty

python:
  - "2.7"

install:
  - sudo pip install ansible
  - sudo bash ./install.sh --no-requirements-check
  - cd /usr/local/share/cikit
  - sudo git fetch origin ${TRAVIS_BRANCH}
  - sudo git checkout ${TRAVIS_BRANCH}

script:
#  - sudo bash ./tests/travis/inventory.sh
  - cikit init --project=test_project
  - cd test_project
  - sudo ANSIBLE_INVENTORY="localhost," cikit provision --limit=localhost
