---
# http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes-in-2-0
- set_fact:
    list: "{{ item }}"

- shell: "a2{{ item.key }}{{ list.key | regex_replace('s$', '') }} {{ item.value | join(' ') }}"
  args:
    warn: no
  when: "{{ item.value | count }}"
  with_dict: "{{ list.value }}"
