---
# The "list" variable must have the following structure:
# list:
#   [conf|mods|sites]:
#     [en|dis]:
#       - item1
#       - ...
#       - itemN
- shell: "a2{{ item.key }}{{ list.key | regex_replace('s$', '') }} {{ item.value | join(' ') }}"
  args:
    warn: no
  when: item.value | count
  with_dict: "{{ list.value }}"
