---
# The "type" variable must be "conf" or "sites".
- name: 'Create "{{ type }}" configs'
  template:
    src: "{{ type }}/{{ item | basename }}"
    dest: '{{ cikit_apache.dest }}/{{ type }}-available/{{ item | basename | splitext | first }}'
  with_fileglob: "../templates/{{ type }}/*.j2"
