---
- name: Ensure directory for SSL certificates exists
  file:
    path: "{{ ssl.dest }}"
    state: directory
    recurse: yes

- name: Generate Diffie-Hellman certificate for DHE ciphersuites
  shell: "openssl dhparam -out dhparam.pem {{ ssl.bits }}"
  args:
    chdir: "{{ ssl.dest }}"

- name: Create self-signed SSL certificate
  shell: "openssl req -x509 -nodes -days 365 -newkey rsa:{{ ssl.bits }} -subj '/C=US' -keyout ssl.key -out ssl.crt"
  args:
    chdir: "{{ ssl.dest }}"

- include: tasks/copy.yml
  with_items: ["crt", "key"]
  when: ssl.src
