---
- include: tasks/database/database.yml name="Remove databases" state="absent"
- include: tasks/database/database.yml name="Create databases" state="present"
- include: tasks/environment/prepare.yml

- name: Set site domain
  set_fact:
    site_domain: "{{ site_url.split('//') | last }}"

- name: Create config
  template:
    src: templates/wp-config.j2
    dest: "{{ project_workspace }}/{{ settings }}"

- include: tasks/wp.yml name="Installing WordPress" command="core"
  with_items:
    - install:
      - "--url={{ site_url }}"
      - "--title={{ project | capitalize }}"
      - "--admin_user={{ wordpress.user.name }}"
      - "--admin_email={{ wordpress.user.name }}@{{ site_domain }}"
      - "--admin_password={{ wordpress.user.pass }}"
  when: not sql_workflow

# Download and import databases.
- include: tasks/database/import.yml
  with_dict: "{{ databases }}"
  when: sql_workflow and "source" in item.value

# Unique way for both workflows.
- include: tasks/wp.yml name="Set username for super user" command="db"
  with_items:
    - query: ["\"UPDATE wp_users SET user_login = '{{ wordpress.user.name }}' WHERE id = 1\""]

# Unique way for both workflows.
- include: tasks/wp.yml name="Set password for super user" command="user"
  with_items:
    - update:
      # User ID.
      - "1"
      - "--user_pass={{ wordpress.user.pass }}"

- include: tasks/wp.yml name="Set site URL" command="option update"
  with_items:
    - home: ["{{ site_url }}"]
    - siteurl: ["{{ site_url }}"]

- include: tasks/wp.yml name="Update site domain" command="db"
  with_items:
    - query: ["'update wp_site s, wp_blogs b set s.domain = \"{{ site_domain }}\", b.domain = s.domain'"]
  when: sql_workflow

- include: tasks/wp.yml name="Manage plugins" command="plugin"
  with_items: "{{ plugins }}"

- include: tasks/wp.yml name="Execute command"
  with_items: "{{ commands }}"
