---
- include_tasks: tasks/database/database.yml name="Remove databases" state="absent"
- include_tasks: tasks/database/database.yml name="Create databases" state="present"
- include_tasks: tasks/environment/prepare.yml

- name: Set site domain
  set_fact:
    site_domain: "{{ site_url.split('//') | last }}"

- name: Create config
  template:
    src: templates/wp-config.j2
    dest: "{{ project_workspace }}/{{ settings }}"

- include_tasks: tasks/wp.yml
  with_items:
    - name: "Installing WordPress"
      core:
      - "install"
      - "--url={{ site_url }}"
      - "--title={{ project | capitalize }}"
      - "--admin_user={{ wordpress.user.name }}"
      - "--admin_email={{ wordpress.user.name }}@{{ site_domain }}"
      - "--admin_password={{ wordpress.user.pass }}"
  when: not sql_workflow

# Download and import databases.
- include_tasks: tasks/database/import.yml
  with_dict: "{{ databases }}"
  when: "sql_workflow and 'source' in item.value"

- include_tasks: tasks/wp.yml
  with_items:
    - name: "Set a username for a superuser to '{{ wordpress.user.name }}'"
      db: ["query", "'UPDATE wp_users SET user_login = \"{{ wordpress.user.name }}\" WHERE id = 1'"]
    - name: "Set a password for a superuser to '{{ wordpress.user.pass }}'"
      user: ["update", "1", "--user_pass='{{ wordpress.user.pass }}'"]
    - name: "Set home URL"
      option: ["update", "home", "{{ site_url }}"]
    - name: "Set site URL"
      option: ["update", "siteurl", "{{ site_url }}"]
    - name: "Update site domain"
      db: ["query", "'update wp_site s, wp_blogs b set s.domain = \"{{ site_domain }}\", b.domain = s.domain'"]
      if: "{{ sql_workflow }}"

- include_tasks: tasks/bash.yml
  with_items: "{{ commands.bash }}"

- include_tasks: tasks/wp.yml
  with_items: "{{ commands['wp-cli'] }}"
