---
apache_port: 80
apache_port_ssl: 443

apache_vhosts:
  - servername: local.loc
    documentroot: /var/www/html
#    certificate_file: "/path/to/certificate.crt"
#    certificate_key_file: "/path/to/certificate.key"
#    certificate_chain_file: "/path/to/certificate_chain.crt"

apache_data:
  conf:
    en:
      - fqdn.conf
    dis: []
  mods:
    en:
      - rewrite.load
      - ssl.load
      - vhost_alias.load
    dis: []
  sites:
    en:
      - vhosts
    dis:
      - 000-default.conf
