# A custom set of operations could be here. They are will be executed in scope of "sniffers.yml" playbook.
---
- name: Run security review
  shell: |-
    drush en security_review -y
    drush secrev 2>&1 | grep error | awk '{$NF=""}1' > '{{ reports.dir }}/Security review.txt'
    drush {{ 'dis' if core < 8 else 'pmu' }} security_review -y
  args:
    chdir: "{{ project_workspace }}"
  environment: "{{ env_vars }}"
