---
- include_role:
    # Install Gitlab CI if either "--gitlab-ci-token" or "--gitlab-ci-url"
    # is passed. Use Jenkins otherwise.
    name: "cikit-{{ 'gitlab-ci' if gitlab_ci_token | default or gitlab_ci_url | default else 'jenkins' }}"
