---
- name: "{{ name }}"
  become_user: "{{ ansible_user }}"
  shell: |-
    composer global require {{ item.key }}:{{ item.value }} \
      --no-interaction \
      --prefer-dist \
      --no-ansi
  with_dict: "{{ composer_packages }}"
