---
- name: Create global config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"

- name: Create snippets
  template:
    src: "snippets/{{ item | basename }}"
    dest: "{{ nginx_conf_dir }}/snippets/{{ item | basename | splitext | first }}"
  with_fileglob: "../templates/snippets/*.j2"

# Create the virtual hosts for serving Solr, Jenkins etc. on a
# droplet (proxying a request to them).
- include_tasks: vhost.yml template="{{ role_path }}/templates/cikit.j2"
  when: not localhost

# Create a virtual host for serving the application in a case
# Nginx was chosen as a web server for this purpose.
- include_tasks: vhost.yml
  with_first_found:
    # Allow a project to overwrite the template for a virtual host.
    - "{{ __targetdir__ }}/.cikit/templates/nginx/vhosts.conf.j2"
    # If a project didn't define the template we're falling back to the default one.
    - "{{ role_path }}/templates/vhosts.conf.j2"
  loop_control:
    loop_var: template
  when: "'nginx' == web_server"
