---
- name: Create virtual hosts
  template:
    src: "{{ template }}"
    dest: "{{ nginx_conf_dir }}/sites-{{ item }}/{{ template | basename | splitext | first }}"
  with_items: ["enabled", "available"]
