/**
 * @param {Application} app
 *   The application.
 * @param {Object} chai
 *   Chai testing tool.
 *
 * @return {Object.<Function[]>}
 *   The list of functions.
 */
module.exports = (app, chai) => {
  const prefix = app.config.get('prefix');

  /**
   * Prepares the request.
   *
   * @param {String} method
   *   HTTP method in lowercase.
   * @param {String} route
   *   API route.
   *
   * @return {ServerResponse}
   *   The request.
   */
  const request = (method, route) => chai
    .request(app)[method](prefix + '/' + route);

  /**
   * Sends the request for authentication.
   *
   * @param {String|Mongoose.<Model>} username
   *   The name or an object of a user.
   * @param {String|null} code
   *   The code, generated by authenticating app, that needs to be verified.
   *
   * @return {Promise.<ServerResponse>}
   *   The request.
   */
  const auth = (username, code = null) => {
    if ('object' === typeof username && null === code) {
      code = username.generateTotp();
      username = username.username;
    }

    return request('post', 'user/auth')
      .send({username, code});
  };

  /**
   * Prepares an authorized API request.
   *
   * @param {Object} auth
   *   The response of authentication request.
   * @param {String} method
   *   HTTP method in lowercase.
   * @param {String} route
   *   API route.
   *
   * @return {ServerResponse}
   *   The request.
   */
  const api = (auth, method, route) => request(method, route)
    .set('Authorization', auth.body.token_type + ' ' + auth.body.access_token);

  return {
    auth,
    api,
  };
};
