- name: Get the list of migrations
  find:
    paths: "tasks/migrations"
    patterns: '^\d\.\d\.\d\.yml$'
    use_regex: yes
  register: cikit_migrations

- name: Determine the versions of migrations
  set_fact:
    cikit_migrations: "{{ cikit_migrations.files | map(attribute='path') | map('basename') | map('splitext') | map('first') | list }}"

- include_tasks: "{{ item }}.yml"
  with_items: "{{ cikit_migrations }}"
  # This file runs only if a new version of the package is greater than current. This
  # means we have to run only those tasks, which were added only after the current version.
  when: "item is version_compare(cikit_current_version, 'gt')"
