#!/usr/bin/env python

if '__main__' == __name__:
    import sys
    import atexit
    from datetime import datetime
    from os import environ

    if 'CIKIT_SUPPRESS_EXECUTION_TIME' not in environ:
        start = datetime.now()
        atexit.register(lambda: sys.stdout.write('\nExecution time: ' + str(datetime.now() - start) + '\n'))

    try:
        import __init__
    except KeyboardInterrupt:
        sys.exit(1)
