#!/usr/bin/env python

import sys
import atexit
import datetime

start = datetime.datetime.now()


def goodbye():
    execution_time = datetime.datetime.now() - start

    if execution_time >= datetime.timedelta(seconds=55):
        print('\nExecution time: ' + str(execution_time))


atexit.register(goodbye)

try:
    import __init__
except KeyboardInterrupt:
    sys.exit(1)
