---
- name: Configure allowed SSH hosts
  lineinfile:
    regexp: "{{ item.regexp }}"
    state: "{{ item.state }}"
    line: "{{ item.replace }}"
    dest: "/etc/hosts.{{ item.type }}"
    mode: 0644
  with_items:
    - type: deny
      # This trick allows to revert previous changes if configuration changed.
      state: "{{ 'present' if os_configuration.strict_ssh_policy else 'absent' }}"
      regexp: |-
        ^sshd:\s+ALL\s+EXCEPT.*$
      replace: |-
        sshd: ALL EXCEPT {{ allowed_hosts | join(' ') }}
    # Never do not allow SSH access for all.
    - type: allow
      state: "{{ 'absent' if os_configuration.strict_ssh_policy else 'present' }}"
      regexp: |-
        ^sshd:\s+ALL
      replace: |-
        sshd: ALL
