---
- name: Create directory for VM
  file:
    path: "{{ virtualmachine.path }}"
    state: directory
    owner: "{{ phpvirtualbox.users.system.name }}"
    recurse: yes

- name: Download and unarchive VM
  unarchive:
    src: "{{ virtualmachine.package }}"
    dest: "{{ virtualmachine.path }}"
    copy: no
    owner: "{{ phpvirtualbox.users.system.name }}"

- include: check.yml
