---
- include_tasks: disallow-web-server-change.yml
  when: not localhost

- name: Eliminate web servers conflicts
  service:
    name: "{{ item }}"
    # Stop conflicting web server.
    state: stopped
    # Prevent conflicting web server to be started on boot.
    enabled: no
  # Apply the rule for any web server, except currently selected.
  when: web_server != item
  with_items: "{{ cikit_webserver.servers }}"
  # If feasible conflicting server is not installed then the task will end up in error.
  ignore_errors: yes

- include_tasks: "{{ operation_place }}.yml"
