---
- name: Define an empty list
  set_fact:
    cikit_matrices_new: {}

- name: Delete matrix definition
  set_fact:
    cikit_matrices_new: "{{ cikit_matrices | combine({item.key: item.value}) }}"
  with_dict: "{{ cikit_matrices }}"
  when: item.key != matrix

- name: Prepare a list of matrices
  set_fact:
    cikit_matrices: "{{ cikit_matrices_new }}"
