---
- name: Ensure folder to protect with HTTP auth exists
  file:
    path: "{{ protected_folder.path }}"
    state: directory
    owner: www-data
    group: adm

- name: Generate .htaccess
  template:
    src: htaccess.j2
    dest: "{{ protected_folder.path }}/.htaccess"

- name: Generate .htpasswd
  htpasswd:
    path: "{{ protected_folder.path }}/.htpasswd"
    name: "{{ protected_folder.user }}"
    password: "{{ protected_folder.pass }}"
