---
- name: Install Composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir={{ composer_bin }}"
  args:
    warn: no

- name: Rename PHAR file
  shell: "mv composer.phar composer"
  args:
    chdir: "{{ composer_bin }}"

- name: Make Composer executable
  file:
    path: "{{ composer_bin }}/composer"
    mode: 0755

- name: Prepare directory for global Composer packages
  file:
    path: "{{ composer_dir }}"
    state: directory

- name: Install system packages
  include: packages.yml
  args:
    composer_packages: "{{ composer_packages_system }}"

- name: Create .config directory
  file:
    path: "{{ user_home.stdout }}/.config/composer"
    state: directory
    recurse: yes

- name: Create Composer config
  template:
    src: config.json.j2
    dest: "{{ user_home.stdout }}/.config/composer/config.json"

- name: Install packages
  include: packages.yml

- name: Determine Composer packages
  shell: ls -A {{ composer_dir }}/vendor/bin/ | grep -v '\..*'
  register: packages

- name: Make Composer packages executable
  file:
    src: "{{ composer_dir }}/vendor/bin/{{ item }}"
    dest: "{{ composer_bin }}/{{ item }}"
    state: link
  when: "{{ item != 'composer' }}"
  with_items: "{{ packages.stdout_lines if 'stdout_lines' in packages else [] }}"

- name: Mark role as executed
  set_fact:
    ansible_composer_role_executed: yes
