---
- include_tasks: template.yml
  with_items:
    - conf
    - sites
  loop_control:
    loop_var: type

- name: Configure ports
  template:
    src: "ports.conf.j2"
    dest: "{{ cikit_apache.dest }}/ports.conf"

- include_tasks: a2.yml
  with_dict: "{{ apache_data }}"
  loop_control:
    loop_var: list
