---
- include_tasks: create-configs.yml
  with_dict:
    conf: "conf-available/"
    common: ""
  loop_control:
    loop_var: dir

- name: Create virtual hosts
  template:
    src: "{{ item }}"
    # Do not add the config to "sites-enabled" since it'll be done later.
    dest: "{{ cikit_apache.dest }}/sites-available/{{ item | basename | splitext | first }}"
  with_first_found:
    # Allow a project to overwrite the template for a virtual host.
    - "{{ __targetdir__ }}/.cikit/templates/apache2/vhosts.conf.j2"
    # If a project didn't define the template we're falling back to the default one.
    - "{{ role_path }}/templates/vhosts.conf.j2"

- include_tasks: a2.yml
  with_dict: "{{ apache_data }}"
  loop_control:
    loop_var: list
