---
- name: Ensure access
  file:
    mode: "{{ item.mode | default('0755') }}"
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}"
  with_items:
    - path: "{{ tmproot }}"
      mode: "1777"
    - path: "{{ webroot }}/backup"
    - path: "{{ project_workspace }}/{{ filesystem }}"
    - path: "{{ project_workspace }}/{{ settings }}"
      mode: "0664"
      state: touch
