# ro:limit
---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - "{{ __targetdir__ }}/.cikit/config.yml"

  vars:
    install: no

  pre_tasks:
    - include: tasks/project-variable.yml

    - include_vars: "{{ item }}"
      with_fileglob: "{{ __targetdir__ }}/cikit/vars/*.yml"

    - name: Set name for Jenkins job
      set_fact:
        jenkins_job: "{{ project }}"
        jenkins_install: "{{ install | bool }}"

  roles:
    - role: cikit-jenkins
