---
- hosts: all
  become: yes
  gather_facts: no

  environment:
    DEBIAN_FRONTEND: noninteractive

  vars_files:
    - ../config.yml
    - vars/ruby.yml
    - vars/solr.yml
    - vars/ports.yml
    - vars/mysql.yml
    - vars/nginx.yml
    - vars/apache.yml
    - vars/security.yml

  vars_prompt:
    - name: php_version
      prompt: Which version of PHP you'd want to install? (5.6/7.0/7.1)
      default: 7.1
      private: no
      tags: ["php", "php-stack"]

    - name: nodejs_version
      prompt: Which version of Node.js you'd want to install? (4/5/6/7)
      default: 6
      private: no
      tags: ["nodejs", "phantomjs"]

    - name: ruby_version
      prompt: Which version of Ruby you'd want to install? (2.1.10/2.2.6/2.3.3/2.4.0)
      default: 2.4.0
      private: no
      tags: ["sniffers", "ruby"]

    - name: solr_version
      prompt: Which version of Solr you'd want to install? (5.5.4/6.5.1/no)
      default: "no"
      private: no
      tags: ["solr"]

  vars:
    credentials_storage: ../cikit-credentials

    basic_packages:
      apt:
        - git
        - tar
        - vim
        - curl
        - htop
        - make
        - time
        - tree
        - rsync
        - unzip
        # Needs to be installed explicitly in case of very basic Ubuntu.
        - sudo
        - lsof
        - iputils-ping
        - python
        - python-dev
        - python-pycurl
        - python-passlib
        - python-simplejson
        - python-software-properties
        - libmagickcore-dev
        - libmagickwand-dev
        - libmysqlclient-dev
        - imagemagick
        - apparmor-utils
        - bsdutils
        - build-essential
        - software-properties-common
        - libffi-dev
        - libssl-dev
        - rng-tools
        - zlib1g-dev
        # Needed for "rbenv".
        - libreadline-dev

      pip:
        - setuptools
        - paramiko
        - pyyaml
        - jinja2
        - markupsafe
        - MySQL-python
        - ansible

  pre_tasks:
    - name: Check Ansible compatibility
      fail:
        msg: "Continuation is possible only with Ansible 2.2.x on host machine."
      when: "ansible_version.major < 2 and ansible_version.minor < 2"
      tags: ["always"]

    - name: Check whether provision running for local environment
      set_fact:
        localhost: "{{ ansible_host is defined and '127.0.0.1' == ansible_host }}"
      tags: ["always"]

    - include: tasks/password.yml
      args:
        title: "Compute password for basic HTTP authentication"
        name: http_auth_pass
        for: "{{ http_auth_pass }}"
      when: not localhost
      tags: ["always"]

    - name: Ensure Python is installed on remote host
      # We must use "raw" instead of "shell" here due to the following:
      # FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to <HOST>", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found", "msg": "MODULE FAILURE", "rc": 0}
      raw: "[ $(which python) ] || (apt update -y && apt install python-minimal -y)"
      when: not localhost
      tags: ["always"]

      # "gather_facts" after performing required tasks.
      # See https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f#gistcomment-1869582
    - name: Gather facts
      setup: ~
      tags: ["always"]

    - name: Check whether provision running for Docker container
      set_fact:
        docker: "{{ 'docker' == ansible_virtualization_type }}"
      tags: ["always"]

    - name: Obtain home directory of "{{ ansible_user }}" user
      shell: "eval echo ~{{ ansible_user }}"
      register: user_home
      tags: ["always"]

    - include: tasks/project-variable.yml
      when: not localhost and not jenkins_reinstall_deb
      tags: ["jenkins"]

    - name: Set name for Jenkins job
      set_fact:
        jenkins_job: "{{ project }}"
      when: not localhost
      tags: ["jenkins"]

    - name: Configure hostname
      hostname:
        name: "{{ inventory_hostname }}"
      # It's not possible to set the hostname for Docker container. The "-h"
      # option ought to be used instead.
      # https://github.com/moby/moby/issues/9295#issuecomment-140350434
      when: not localhost and not docker
      tags: ["always"]

    - name: Create CIKit command line utility
      file:
        src: "{{ webroot }}/cikit"
        dest: /usr/bin/cikit
        state: link
      when: localhost

    - name: Generate Bash completion for CIKit utility
      template:
        src: templates/cikit.complete.sh.j2
        dest: /etc/bash_completion.d
      when: localhost

    - name: Process facts
      set_fact: {"install_{{ item.key }}": "{{ item.value not in ['no', false] }}"}
      with_dict:
        solr: "{{ solr_version }}"
      tags: ["always"]

    - name: Spoof Sendmail if not installed
      file:
        src: /bin/true
        path: /usr/sbin/sendmail
        state: link
        force: no

    # https://github.com/propeoplemd/cibox/pull/349
    - name: Recover possible fail
      shell: yes | dpkg --configure -a
      ignore_errors: yes

    - name: Install APT packages
      apt:
        name: "{{ item }}"
        state: present
      register: cikit_apt_needs_cache_update
      with_items: "{{ basic_packages.apt }}"

    - name: Update APT cache
      apt:
        update_cache: yes
      # Update cache only if new packages were installed.
      when: cikit_apt_needs_cache_update.changed

    - name: Install EasyInstall and PIP
      shell: "[ $(which {{ item.tool }}) ] || {{ item.script }}"
      args:
        warn: no
        executable: /bin/bash
      # "with_dict" cannot be used since ordering of operations is important!
      with_items:
        - tool: easy_install
          script: "curl -s https://raw.githubusercontent.com/ActiveState/ez_setup/v0.9/ez_setup.py | python"

        - tool: pip
          script: "easy_install pip"

    - name: Install PIP packages
      pip:
        name: "{{ item }}"
        state: latest
      with_items: "{{ basic_packages.pip }}"

  roles:
    - role: cikit-security
      tags: ["security"]

    - role: cikit-nginx
      when: not localhost
      tags: ["nginx", "php-stack", "security"]

    - role: cikit-apache
      tags: ["apache", "php-stack"]

    - role: cikit-php
      tags: ["php", "php-stack"]

    - role: cikit-nodejs
      tags: ["nodejs"]

    - role: cikit-phantomjs
      tags: ["phantomjs"]

    - role: cikit-composer
      tags: ["composer", "php-stack"]

    - role: cikit-mysql
      tags: ["mysql", "php-stack"]

    - role: cikit-java
      tags: ["java", "solr", "sniffers", "jenkins"]

    - role: cikit-solr
      when: install_solr
      tags: ["solr", "php-stack"]

    - role: cikit-ruby
      tags: ["sniffers", "ruby"]

    - role: cikit-sniffers
      tags: ["sniffers", "php-stack"]

    - role: ansible-role-memcached
      tags: ["memcache", "php-stack"]

    - role: cikit-selenium
      tags: ["selenium"]

    - role: cikit-jenkins
      when: not localhost
      tags: ["jenkins"]

  tasks:
    - name: Starting random rnd-tools service
      shell: rngd -r /dev/urandom
      when: not localhost and 'openvz' != ansible_virtualization_type
      tags: ["always"]

    - name: Restart service
      service:
        name: "{{ item }}"
        state: restarted
      ignore_errors: yes
      with_items: ["apache2", "nginx"]
      tags: ["always"]
