---
- hosts: localhost
  connection: local
  gather_facts: no

  # List of variables that allowed to be changed via command line arguments.
  vars:
    # You can use "--version=issues/62" to get the codebase from specific branch/tag.
    version: HEAD
    # While developing the package you can use "--repository=git@github.com:BR0kEN-/cikit.git"
    # to get the codebase by SSH or from a fork.
    repository: https://github.com/BR0kEN-/cikit.git

  tasks:
    - name: Define variables
      set_fact:
        cikit_location: "{{ (playbook_dir + '/..') | realpath }}"

    - name: Update the package
      git:
        repo: "{{ repository }}"
        dest: "{{ cikit_location }}"
        update: yes
        version: "{{ version }}"
        recursive: yes
        track_submodules: no

    - name: Get the version of an updated package
      set_fact:
        # Read the version of the package we've just updated to.
        cikit_version: "{{ lookup('file', cikit_location + '/version.txt') }}"

    - name: Get the list of migrations
      find:
        paths: "{{ playbook_dir }}/tasks/migrations"
        patterns: '^\d\.\d\.\d\.yml$'
        use_regex: yes
      register: cikit_migrations

    - name: Determine the versions of migrations
      set_fact:
        cikit_migrations: "{{ cikit_migrations.files | map(attribute='path') | map('basename') | map('splitext') | map('first') | list }}"

    - include_tasks: "tasks/migrations/{{ item }}.yml"
      with_items: "{{ cikit_migrations }}"
      when: "item | version_compare(cikit_version, '>')"
