---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Update the CIKit package
      git:
        repo: https://github.com/BR0kEN-/cikit.git
        dest: ../
        update: yes
        recursive: yes
        track_submodules: no

    - name: Set the correct path to executable
      file:
        src: "{{ (playbook_dir + '/../bin/cikit') | realpath }}"
        dest: /usr/local/bin/cikit
        mode: a+x
        force: yes
