---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Update the CIKit package
      git:
        repo: https://github.com/BR0kEN-/cikit.git
        dest: ../
        force: yes
        update: yes
        recursive: yes
        track_submodules: no
