---
- name: "{{ title | default('Generate password') }}"
  set_fact: {
    "{{ name }}": "{{ for if for else lookup('password', credentials_storage + '/' + (limit | default(inventory_hostname)) + '/' + name + ' length=16') }}"
  }
