---
- name: Configure MOTD
  template:
    src: "{{ item }}"
    dest: "/etc/update-motd.d/{{ item | basename | splitext | first }}"
    mode: 0755
  with_fileglob: templates/motd/*.j2

- name: Check whether SSH daemon is installed
  stat:
    path: /etc/ssh/sshd_config
  register: ssh_config

- include_tasks: tasks/tasks/sshd.yml
  when: ssh_config.stat.exists

- import_tasks: tasks/tasks/hosts.yml
