# This list of tasks depends on variables:
# - name: the name of group from inventory file.
# Used built-in variables:
# - hostvars: list of groups from inventory file.
---
- name: "Check for {{ name }} hostname"
  fail:
    msg: "{{ name }} hostname is undefined. Configure it inside of inventory file in [{{ name }}] group."
  when: name not in hostvars

- name: "Build SSH aguments for the {{ hostvars[name].ansible_host }} host"
  set_fact:
    hostname_ssh:
      host: "{{ hostvars[name].ansible_user }}@{{ hostvars[name].ansible_host }}"
      args: "{{ '-i ' + hostvars[name].ansible_ssh_private_key_file.replace('~', become_home) if 'ansible_ssh_private_key_file' in hostvars[name] else '' }} -S none -o StrictHostKeyChecking=no {{ '-p ' + hostvars[name].ansible_port | string if 'ansible_port' in hostvars[name] else '' }}"

- name: Ensure permission for SSH key is appropriate
  file:
    path: "{{ hostvars[name].ansible_ssh_private_key_file }}"
    mode: u=r,go-rw
  when: "'ansible_ssh_private_key_file' in hostvars[name]"
