# This list of tasks depends on the variables:
# - name: the name of a group from inventory.
# Used built-in variables:
# - hostvars: lists of variables for each group.
# - groups: list of inventory group names.
---
- name: "Check for the {{ name }} host"
  fail:
    msg: "The '{{ name }}' host is undefined. Add it outside of the VM using 'cikit host/add --alias={{ name }}'"
  when: name not in groups

- name: Compute the data of a host
  set_fact:
    hostdata: "{{ hostvars[groups[name] | first] }}"

- name: "Build SSH arguments for the '{{ hostdata.inventory_hostname }}' host"
  set_fact:
    hostname_ssh:
      host: "{{ hostdata.ansible_user }}@{{ hostdata.inventory_hostname }}"
      args: >-
        {{ "-i '" + hostdata.ansible_ssh_private_key_file.replace("~", become_home) + "'" if "ansible_ssh_private_key_file" in hostdata else "" }}
        {{ "-p " + hostdata.ansible_port | string if "ansible_port" in hostdata else '' }}
        -o StrictHostKeyChecking=no
        -S none

- name: Ensure permissions for SSH key is appropriate
  file:
    path: "{{ hostdata.ansible_ssh_private_key_file }}"
    mode: u=r,go-rw
  when: "'ansible_ssh_private_key_file' in hostdata"
