# Used variables:
# - become_name: the name of user, who triggered this script.
# - become_home: the home directory of user, who triggered this script.
# - dump_local_path: the path to created snapshot on a local machine.
#
# Used built-in variables:
# - hostvars: list of data for all defined hosts.
---
- include_tasks: ../../get-hostname.yml
  vars:
    name: "{{ item.value.source.from }}"

# The "mysql_db" module isn't used because the "mysqldb" module for Python might not be installed on remote.
- name: Create a snapshot
  shell: >
    ssh {{ hostname_ssh.args }} {{ hostname_ssh.host }} "mysqldump -P{{ item.value.source.port | default(3306) }} -h{{ item.value.source.host | default('127.0.0.1') }} -u{{ item.value.source.user | default(mysql.user) }} -p{{ item.value.source.pass | default(mysql.pass) }} {{ item.value.source.db }} | gzip -c" > {{ dump_local_path }}
  register: _snapshot_result

- name: Remove broken snapshot
  file:
    path: "{{ dump_local_path }}"
    state: absent
  when: "'error' in _snapshot_result.stderr"

- name: Snapshot creation failed
  fail:
    msg: "{{ _snapshot_result.stderr }}"
  when: "'error' in _snapshot_result.stderr"
