---
- name: Build installation instructions
  shell: "curl -sL https://deb.nodesource.com/setup_{{ cikit_nodejs_version | int }}.x | sudo -E bash -"
  args:
    warn: no

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Mark role as executed
  set_fact:
    cikit_nodejs_role_executed: yes
