url: http://cikit.tools
name: &name "Sergii Bondarenko"
title: "CIKit"
title_long: "Continuous Integration Kit"
locale: "en-US"
# https://help.github.com/articles/repository-metadata-on-github-pages/#using-repository-metadata-locally
repository: BR0kEN-/cikit
description: "Ansible-based system for building environments for local development and continuous integration."
title_separator: "|"

search: true
breadcrumbs: true
words_per_minute: 200

cikit_parent:
  url: "http://cibox.tools"
  title: "CIBox"
  title_long: "Continuous Integration Box"
  author:
    name: "Andrii Podanenko"
    github: "podarok"

twitter:
  username: &twitter "brO_0keN"

facebook:
  username: &facebook "alwayswannarock"
  app_id:
  publisher:
og_image: "/assets/site-logo.png"

social:
  links:
    - "https://twitter.com/brO_0keN"
    - "https://facebook.com/alwayswannarock"

author:
  # *name is a YAML reference pointing to the &anchor earlier.
  name: *name
  avatar: "/assets/BR0kEN.jpg"
  location: "Dnipro, Ukraine"
  email: sb@firstvector.org
  bitbucket: BR0kEN
  facebook: *facebook
  github: BR0kEN-
  linkedin: BR0kEN
  twitter: *twitter

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
  - "*.png"
  - "*.patch"
  - "*.sh"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  documentation:
    output: true
  changelog:
    output: true


# Defaults.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      share: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

  - scope:
      path: "_documentation"
      type: documentation
    values:
      toc: true
      toc_label: Page contents
      layout: single
      sidebar:
        nav: "documentation"

  - scope:
      path: "_changelog"
      type: changelog
    values:
      toc: true
      toc_label: Page contents
      layout: single
      sidebar:
        nav: "documentation"

# Sass/SCSS.
sass:
  sass_dir: _sass
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed


# Outputting.
permalink: /blog/:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Kiev


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-redirect-from

# https://help.github.com/articles/configuring-jekyll-plugins/
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-redirect-from


relative_links:
  enabled: true
  collections: true


optional_front_matter:
  enabled: true


comments:
  provider: disqus
  disqus:
    shortname: cikit-tools

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression.
# http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
