---
- name: Get the list of all droplets
  shell: "docker ps -a | grep {{ application }}"
  register: droplets
  # An empty list will return the "1" exit code.
  failed_when: droplets.rc > 1

- name: Store the list of all droplets
  set_fact:
    output: "{{ droplets.stdout_lines }}"
