---
- name: Configure php.ini
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_version }}/{{ item.key }}php.ini"
  with_dict:
    /: global
    cli/: cli
    fpm/: global
    apache2/: global

- name: Configure extension
  template:
    src: extension.ini.j2
    dest: "/etc/php/{{ php_version }}/mods-available/{{ item.key }}.ini"
  with_dict: "{{ php_extensions }}"

- include_tasks: fixtures/link-extension.yml
  with_items: ["cli", "fpm", "apache2"]
  loop_control:
    loop_var: type
