---
- name: Configure php.ini
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ cikit_php_version }}/{{ item.key }}php.ini"
  with_dict:
    /: global
    cli/: cli
    apache2/: global

- name: Configure extension
  template:
    src: extension.ini.j2
    dest: "/etc/php/{{ cikit_php_version }}/mods-available/{{ item.key }}.ini"
  with_dict: "{{ cikit_php.extensions }}"

- name: Link extension configuration for Apache2
  file:
    src: "/etc/php/{{ cikit_php_version }}/mods-available/{{ item.key }}.ini"
    dest: "/etc/php/{{ cikit_php_version }}/apache2/conf.d/20-{{ item.key }}.ini"
    state: link
  with_dict: "{{ cikit_php.extensions }}"

- name: Link extension configuration for CLI
  file:
    src: "/etc/php/{{ cikit_php_version }}/mods-available/{{ item.key }}.ini"
    dest: "/etc/php/{{ cikit_php_version }}/cli/conf.d/20-{{ item.key }}.ini"
    state: link
  with_dict: "{{ cikit_php.extensions }}"
