---
- name: Fail if version is unsupported
  fail:
    msg: "PHP of {{ php_version }} version is unsupported. Choose between {{ cikit_php.versions | join(', ') }}"
  when: php_version not in cikit_php.versions

- name: Add APT repository
  apt_repository:
    repo: "{{ php.repo }}"

- name: Update APT cache
  apt:
    update_cache: yes

# Allow modifying these variables by tasks.
- set_fact:
    php_extensions: "{{ php.extensions }}"
    php_packages: "{{ php.packages }}"

- name: Avoid installation of deprecated packages
  set_fact:
    # Remove the packages for the specific version of PHP.
    php_packages: "{{ php.packages | difference(cikit_php.removed_packages[php_version]) }}"
  when: php_version in cikit_php.removed_packages

- name: Install PHP packages
  shell: "apt-get install php{{ php_version }}-{{ php_packages | join(' php' + php_version + '-') }} -y"
  args:
    warn: no

- name: Install uncommon PHP packages
  shell: "apt-get install -y {{ cikit_php_extra.packages | join(' ') }}"
  when: cikit_php_extra.packages|length > 0
  args:
    warn: no

- name: Set interpreter version as system default
  shell: "ln -fs /usr/bin/{{ item }}{{ php_version }} /etc/alternatives/{{ item }}"
  args:
    warn: no
  with_items: ["php", "phpize", "php-config"]

- import_tasks: xdebug.yml

- include_tasks: sqlsrv.yml
  # The SQLSRV ODBC driver for Linux is available only for limited versions
  # of OS and is not available for PHP lower than 7.
  # The "install_mssql" variable is flowing from "provision.yml".
  when: "install_mssql is defined and install_mssql and '5.6' != php_version"

- include_tasks: "{{ web_server }}/pre-configure.yml"
- import_tasks: configure.yml
- include_tasks: "{{ web_server }}/post-configure.yml"
