---
- name: Fail if version is unsupported
  fail:
    msg: "PHP of {{ php_version }} version is unsupported. Choose between {{ cikit_php.versions | join(', ') }}"
  when: php_version not in cikit_php.versions

- name: Add APT repository
  apt_repository:
    repo: "{{ php.repo }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install PHP packages
  shell: "apt-get install php{{ php_version }}-{{ php.packages | join(' php' + php_version + '-') }} -y"
  args:
    warn: no

- name: Set interpreter version as system default
  shell: "ln -fs /usr/bin/{{ item }}{{ php_version }} /etc/alternatives/{{ item }}"
  args:
    warn: no
  with_items: ["php", "phpize", "php-config"]

- set_fact:
    # Allow modifying this variable by included tasks.
    php_extensions: "{{ php.extensions }}"
    php_conf_dir: "/etc/php/{{ php_version }}"

- import_tasks: xdebug.yml

- include_tasks: sqlsrv.yml
  # The SQLSRV ODBC driver for Linux is available only for limited versions
  # of OS and is not available for PHP lower than 7.
  # The "install_mssql" variable is flowing from "provision.yml".
  when: "install_mssql is defined and install_mssql and '5.6' != php_version"

# General tweaking for a web server.
- include_tasks: "{{ web_server }}/main.yml"
# Environment-dependent tweaking for a web server.
- include_tasks: "{{ web_server }}/{{ operation_place }}.yml"

- import_tasks: configure.yml
