---
- name: Fail if version is unsupported
  fail:
    msg: "PHP of {{ php_version }} version is unsupported. Choose between {{ cikit_php.versions | join(', ') }}"
  when: "{{ php_version not in cikit_php.versions }}"

- name: Add APT repository
  apt_repository:
    repo: "{{ php.repo }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install PHP packages
  shell: "apt-get install php{{ php_version }}-{{ php.packages | join(' php' + php_version + '-') }} -y"
  args:
    warn: no

- name: Install Apache module for PHP
  apt:
    name: "libapache2-mod-php{{ php_version }}"
    state: latest

- name: Set interpreter version as system default
  shell: "ln -fs /usr/bin/{{ item }}{{ php_version }} /etc/alternatives/{{ item }}"
  with_items: ["php", "phpize", "php-config"]

- include: xdebug.yml
- include: configure.yml

- name: Enalbe PHP for Apache
  shell: "a2dismod php* && a2enmod php{{ php_version }}"
  ignore_errors: yes
